import type { Framework, Control, Evidence, Risk, Report, ReportTemplate, Notification, MissingEvidence, ResilienceScore, GapAnalysis, AuditEvent } from './types';

// ==================== FRAMEWORK DATA ====================
export const frameworks: Framework[] = [
  {
    id: 'fw-iso27001',
    name: 'ISO 27001',
    version: '2022',
    status: 'active',
    compliance: 78,
    controlsTotal: 93,
    controlsCovered: 73,
    evidenceLinked: 312,
    riskLevel: 'medium',
    lastSync: '2025-01-15T10:30:00Z',
    description: 'International standard for information security management systems (ISMS)',
    domains: [
      { id: 'd-iso-org', name: 'Organizational', frameworkId: 'fw-iso27001', categories: [
        { id: 'c-iso-a5', name: 'Information Security Policies', domainId: 'd-iso-org', controls: [] },
        { id: 'c-iso-a6', name: 'Organization of Information Security', domainId: 'd-iso-org', controls: [] },
      ]},
      { id: 'd-iso-people', name: 'People', frameworkId: 'fw-iso27001', categories: [] },
      { id: 'd-iso-physical', name: 'Physical', frameworkId: 'fw-iso27001', categories: [] },
      { id: 'd-iso-technological', name: 'Technological', frameworkId: 'fw-iso27001', categories: [] },
    ],
  },
  {
    id: 'fw-gdpr',
    name: 'GDPR',
    version: '2016/679',
    status: 'active',
    compliance: 85,
    controlsTotal: 46,
    controlsCovered: 39,
    evidenceLinked: 198,
    riskLevel: 'low',
    lastSync: '2025-01-15T09:45:00Z',
    description: 'General Data Protection Regulation for EU data privacy',
    domains: [
      { id: 'd-gdpr-principles', name: 'Principles', frameworkId: 'fw-gdpr', categories: [] },
      { id: 'd-gdpr-rights', name: 'Rights of Data Subjects', frameworkId: 'fw-gdpr', categories: [] },
      { id: 'd-gdpr-controllers', name: 'Controllers & Processors', frameworkId: 'fw-gdpr', categories: [] },
    ],
  },
  {
    id: 'fw-nist',
    name: 'NIST CSF',
    version: '2.0',
    status: 'active',
    compliance: 71,
    controlsTotal: 106,
    controlsCovered: 75,
    evidenceLinked: 267,
    riskLevel: 'high',
    lastSync: '2025-01-14T16:20:00Z',
    description: 'National Institute of Standards and Technology Cybersecurity Framework',
    domains: [
      { id: 'd-nist-gov', name: 'Govern', frameworkId: 'fw-nist', categories: [] },
      { id: 'd-nist-id', name: 'Identify', frameworkId: 'fw-nist', categories: [] },
      { id: 'd-nist-protect', name: 'Protect', frameworkId: 'fw-nist', categories: [] },
      { id: 'd-nist-detect', name: 'Detect', frameworkId: 'fw-nist', categories: [] },
      { id: 'd-nist-respond', name: 'Respond', frameworkId: 'fw-nist', categories: [] },
      { id: 'd-nist-recover', name: 'Recover', frameworkId: 'fw-nist', categories: [] },
    ],
  },
  {
    id: 'fw-dpdp',
    name: 'DPDP',
    version: '2023',
    status: 'active',
    compliance: 62,
    controlsTotal: 38,
    controlsCovered: 24,
    evidenceLinked: 89,
    riskLevel: 'high',
    lastSync: '2025-01-13T14:10:00Z',
    description: 'Digital Personal Data Protection Act, India',
    domains: [
      { id: 'd-dpdp-consent', name: 'Consent Management', frameworkId: 'fw-dpdp', categories: [] },
      { id: 'd-dpdp-processing', name: 'Data Processing', frameworkId: 'fw-dpdp', categories: [] },
    ],
  },
  {
    id: 'fw-pci',
    name: 'PCI-DSS',
    version: '4.0',
    status: 'active',
    compliance: 69,
    controlsTotal: 64,
    controlsCovered: 44,
    evidenceLinked: 156,
    riskLevel: 'critical',
    lastSync: '2025-01-15T08:00:00Z',
    description: 'Payment Card Industry Data Security Standard',
    domains: [
      { id: 'd-pci-network', name: 'Network Security', frameworkId: 'fw-pci', categories: [] },
      { id: 'd-pci-data', name: 'Data Protection', frameworkId: 'fw-pci', categories: [] },
      { id: 'd-pci-vuln', name: 'Vulnerability Management', frameworkId: 'fw-pci', categories: [] },
    ],
  },
];

// ==================== CONTROL DATA ====================
export const controls: Control[] = [
  {
    id: 'ctrl-001', controlRef: 'A.5.1.1', title: 'Information Security Policy', description: 'A policy for information security shall be defined and approved by top management.',
    frameworkId: 'fw-iso27001', domain: 'Organizational', category: 'Information Security Policies',
    owner: 'CISO Office', priority: 'high', complianceStatus: 'compliant', evidenceCount: 5,
    riskMapping: ['RISK-001', 'RISK-003'], lastValidation: '2025-01-10T12:00:00Z',
    mappedControls: [
      { framework: 'NIST CSF', controlRef: 'ID.GV-1', title: 'Governance Policy', confidence: 0.92 },
      { framework: 'GDPR', controlRef: 'Art. 24', title: 'Controller Responsibility', confidence: 0.85 },
    ],
    requiredEvidence: 3, availableEvidence: 5, missingEvidence: 0, confidence: 0.95,
  },
  {
    id: 'ctrl-002', controlRef: 'A.5.1.2', title: 'Review of Information Security Policy', description: 'The information security policy shall be reviewed at planned intervals or if significant changes occur.',
    frameworkId: 'fw-iso27001', domain: 'Organizational', category: 'Information Security Policies',
    owner: 'CISO Office', priority: 'medium', complianceStatus: 'partially_compliant', evidenceCount: 2,
    riskMapping: ['RISK-002'], lastValidation: '2024-12-15T09:30:00Z',
    mappedControls: [
      { framework: 'NIST CSF', controlRef: 'ID.GV-2', title: 'Policy Review', confidence: 0.88 },
    ],
    requiredEvidence: 3, availableEvidence: 2, missingEvidence: 1, confidence: 0.78,
  },
  {
    id: 'ctrl-003', controlRef: 'A.6.1.1', title: 'Information Security Roles and Responsibilities', description: 'All information security responsibilities shall be defined and allocated.',
    frameworkId: 'fw-iso27001', domain: 'Organizational', category: 'Organization of Information Security',
    owner: 'HR Security', priority: 'high', complianceStatus: 'compliant', evidenceCount: 4,
    riskMapping: ['RISK-004'], lastValidation: '2025-01-08T14:00:00Z',
    mappedControls: [
      { framework: 'NIST CSF', controlRef: 'ID.GV-2', title: 'Roles & Responsibilities', confidence: 0.90 },
      { framework: 'PCI-DSS', controlRef: 'Req 12.1', title: 'Security Policy Establishment', confidence: 0.87 },
    ],
    requiredEvidence: 3, availableEvidence: 4, missingEvidence: 0, confidence: 0.92,
  },
  {
    id: 'ctrl-004', controlRef: 'A.8.1.1', title: 'Asset Inventory', description: 'Assets associated with information and information processing facilities shall be identified and an inventory of these assets shall be drawn up and maintained.',
    frameworkId: 'fw-iso27001', domain: 'Organizational', category: 'Asset Management',
    owner: 'IT Operations', priority: 'critical', complianceStatus: 'non_compliant', evidenceCount: 0,
    riskMapping: ['RISK-005', 'RISK-006'], lastValidation: '2024-11-20T10:00:00Z',
    mappedControls: [
      { framework: 'NIST CSF', controlRef: 'ID.AM-1', title: 'Physical Devices Inventory', confidence: 0.95 },
      { framework: 'PCI-DSS', controlRef: 'Req 2.4', title: 'System Component Inventory', confidence: 0.91 },
    ],
    requiredEvidence: 4, availableEvidence: 0, missingEvidence: 4, confidence: 0.0,
  },
  {
    id: 'ctrl-005', controlRef: 'A.8.2.1', title: 'Classification of Information', description: 'Information shall be classified according to the information security needs of the organization based on confidentiality, integrity, and availability.',
    frameworkId: 'fw-iso27001', domain: 'Organizational', category: 'Asset Management',
    owner: 'Data Governance', priority: 'high', complianceStatus: 'partially_compliant', evidenceCount: 2,
    riskMapping: ['RISK-007'], lastValidation: '2025-01-05T11:30:00Z',
    mappedControls: [
      { framework: 'GDPR', controlRef: 'Art. 30', title: 'Records of Processing', confidence: 0.82 },
      { framework: 'DPDP', controlRef: 'Sec 5', title: 'Data Classification', confidence: 0.78 },
    ],
    requiredEvidence: 4, availableEvidence: 2, missingEvidence: 2, confidence: 0.65,
  },
  {
    id: 'ctrl-006', controlRef: 'A.9.1.1', title: 'Access Control Policy', description: 'An access control policy shall be established, documented, and reviewed based on business and information security requirements.',
    frameworkId: 'fw-iso27001', domain: 'Organizational', category: 'Access Control',
    owner: 'IAM Team', priority: 'critical', complianceStatus: 'compliant', evidenceCount: 7,
    riskMapping: ['RISK-008', 'RISK-009'], lastValidation: '2025-01-12T08:00:00Z',
    mappedControls: [
      { framework: 'NIST CSF', controlRef: 'PR.AC-1', title: 'Identity & Credential Management', confidence: 0.94 },
      { framework: 'PCI-DSS', controlRef: 'Req 7.1', title: 'Need-to-Know Access', confidence: 0.93 },
      { framework: 'GDPR', controlRef: 'Art. 32', title: 'Security of Processing', confidence: 0.88 },
    ],
    requiredEvidence: 4, availableEvidence: 7, missingEvidence: 0, confidence: 0.97,
  },
  {
    id: 'ctrl-007', controlRef: 'A.10.1.1', title: 'Encryption Controls', description: 'A policy on the use of cryptographic controls for protection of information shall be defined and implemented.',
    frameworkId: 'fw-iso27001', domain: 'Technological', category: 'Cryptography',
    owner: 'Security Engineering', priority: 'critical', complianceStatus: 'partially_compliant', evidenceCount: 3,
    riskMapping: ['RISK-010'], lastValidation: '2025-01-09T16:45:00Z',
    mappedControls: [
      { framework: 'PCI-DSS', controlRef: 'Req 3.5', title: 'Encryption of Card Data', confidence: 0.96 },
      { framework: 'GDPR', controlRef: 'Art. 32(1)(a)', title: 'Encryption of Personal Data', confidence: 0.91 },
    ],
    requiredEvidence: 5, availableEvidence: 3, missingEvidence: 2, confidence: 0.72,
  },
  {
    id: 'ctrl-008', controlRef: 'A.12.1.1', title: 'Operational Procedures', description: 'Operating procedures for information processing facilities shall be documented and made available to all relevant users.',
    frameworkId: 'fw-iso27001', domain: 'Technological', category: 'Operations Security',
    owner: 'IT Operations', priority: 'medium', complianceStatus: 'compliant', evidenceCount: 4,
    riskMapping: ['RISK-011'], lastValidation: '2025-01-11T13:20:00Z',
    mappedControls: [
      { framework: 'NIST CSF', controlRef: 'PR.IP-1', title: 'Configuration Management', confidence: 0.85 },
    ],
    requiredEvidence: 2, availableEvidence: 4, missingEvidence: 0, confidence: 0.90,
  },
  // GDPR Controls
  {
    id: 'ctrl-009', controlRef: 'Art. 5', title: 'Principles for Processing', description: 'Personal data shall be processed lawfully, fairly and in a transparent manner.',
    frameworkId: 'fw-gdpr', domain: 'Principles', category: 'Lawfulness & Transparency',
    owner: 'DPO Office', priority: 'critical', complianceStatus: 'compliant', evidenceCount: 6,
    riskMapping: ['RISK-012'], lastValidation: '2025-01-14T10:00:00Z',
    mappedControls: [
      { framework: 'DPDP', controlRef: 'Sec 4', title: 'Fair & Transparent Processing', confidence: 0.94 },
      { framework: 'ISO 27001', controlRef: 'A.5.1.1', title: 'Information Security Policy', confidence: 0.80 },
    ],
    requiredEvidence: 4, availableEvidence: 6, missingEvidence: 0, confidence: 0.93,
  },
  {
    id: 'ctrl-010', controlRef: 'Art. 25', title: 'Data Protection by Design', description: 'Data protection principles shall be implemented at the time of the determination of the means for processing.',
    frameworkId: 'fw-gdpr', domain: 'Principles', category: 'Data Protection by Design',
    owner: 'Engineering Security', priority: 'high', complianceStatus: 'non_compliant', evidenceCount: 0,
    riskMapping: ['RISK-013'], lastValidation: '2024-10-15T09:00:00Z',
    mappedControls: [
      { framework: 'DPDP', controlRef: 'Sec 7', title: 'Design Safeguards', confidence: 0.86 },
    ],
    requiredEvidence: 3, availableEvidence: 0, missingEvidence: 3, confidence: 0.0,
  },
  // NIST Controls
  {
    id: 'ctrl-011', controlRef: 'ID.GV-1', title: 'Governance Policy', description: 'Organizational cybersecurity policy is established and communicated.',
    frameworkId: 'fw-nist', domain: 'Govern', category: 'Governance',
    owner: 'CISO Office', priority: 'high', complianceStatus: 'compliant', evidenceCount: 4,
    riskMapping: ['RISK-001'], lastValidation: '2025-01-10T14:00:00Z',
    mappedControls: [
      { framework: 'ISO 27001', controlRef: 'A.5.1.1', title: 'Information Security Policy', confidence: 0.92 },
    ],
    requiredEvidence: 3, availableEvidence: 4, missingEvidence: 0, confidence: 0.91,
  },
  {
    id: 'ctrl-012', controlRef: 'PR.AC-1', title: 'Identity & Credential Management', description: 'Identities and credentials are issued, managed, verified, revoked, and audited for authorized devices and users.',
    frameworkId: 'fw-nist', domain: 'Protect', category: 'Access Control',
    owner: 'IAM Team', priority: 'critical', complianceStatus: 'compliant', evidenceCount: 8,
    riskMapping: ['RISK-008'], lastValidation: '2025-01-12T09:30:00Z',
    mappedControls: [
      { framework: 'ISO 27001', controlRef: 'A.9.1.1', title: 'Access Control Policy', confidence: 0.94 },
      { framework: 'PCI-DSS', controlRef: 'Req 8.1', title: 'User Identification', confidence: 0.90 },
    ],
    requiredEvidence: 4, availableEvidence: 8, missingEvidence: 0, confidence: 0.96,
  },
  // PCI-DSS Controls
  {
    id: 'ctrl-013', controlRef: 'Req 1.1', title: 'Network Security Controls', description: 'Processes and mechanisms for installing and managing network security controls are defined and understood.',
    frameworkId: 'fw-pci', domain: 'Network Security', category: 'Firewall Configuration',
    owner: 'Network Security', priority: 'critical', complianceStatus: 'partially_compliant', evidenceCount: 3,
    riskMapping: ['RISK-014'], lastValidation: '2025-01-07T11:00:00Z',
    mappedControls: [
      { framework: 'NIST CSF', controlRef: 'PR.AC-5', title: 'Network Integrity', confidence: 0.89 },
      { framework: 'ISO 27001', controlRef: 'A.13.1.1', title: 'Network Controls', confidence: 0.87 },
    ],
    requiredEvidence: 5, availableEvidence: 3, missingEvidence: 2, confidence: 0.70,
  },
  {
    id: 'ctrl-014', controlRef: 'Req 3.5', title: 'Encryption of Card Data', description: 'Strong cryptographic algorithms, protocols, and keys are used to protect stored account data.',
    frameworkId: 'fw-pci', domain: 'Data Protection', category: 'Encryption',
    owner: 'Security Engineering', priority: 'critical', complianceStatus: 'compliant', evidenceCount: 5,
    riskMapping: ['RISK-010', 'RISK-015'], lastValidation: '2025-01-13T15:30:00Z',
    mappedControls: [
      { framework: 'ISO 27001', controlRef: 'A.10.1.1', title: 'Encryption Controls', confidence: 0.96 },
      { framework: 'GDPR', controlRef: 'Art. 32(1)(a)', title: 'Encryption of Personal Data', confidence: 0.88 },
    ],
    requiredEvidence: 4, availableEvidence: 5, missingEvidence: 0, confidence: 0.94,
  },
];

// ==================== EVIDENCE DATA ====================
export const evidenceItems: Evidence[] = [
  {
    id: 'EVD-2025-001', asset: 'Core Firewall (FW-001)', source: 'Strike Engine', framework: 'ISO 27001',
    control: 'A.13.1.1', controlRef: 'A.13.1.1', evidenceType: 'automated_scan', validationStatus: 'validated',
    timestamp: '2025-01-15T06:30:00Z', confidenceScore: 0.96, owner: 'Network Security',
    immutableHash: 'sha256:a4f2c8d9e1b3f5a7c9d2e4f6a8b0c3d5e7f9a1b3c5d7e9f0a2b4c6d8e0f1a3',
    description: 'Automated firewall rule validation scan confirming compliance with A.13.1.1 network controls.',
    metadata: { scanType: 'Firewall Rule Audit', scanner: 'CyBreach Strike v3.2', duration: '4m 32s' },
    linkedControls: ['A.13.1.1', 'Req 1.1', 'PR.AC-5'], linkedRisks: ['RISK-014'], linkedReports: ['RPT-2025-001'],
    auditTrail: [
      { id: 'ae-001', timestamp: '2025-01-15T06:30:00Z', module: 'Strike Engine', actor: 'Strike-Scanner-01', hash: 'sha256:gen-a4f2c8', status: 'generated', description: 'Evidence generated from automated scan' },
      { id: 'ae-002', timestamp: '2025-01-15T06:32:15Z', module: 'Validator', actor: 'Validator-Service', hash: 'sha256:val-b5d3e9', status: 'validated', description: 'Evidence validated - all checks passed' },
      { id: 'ae-003', timestamp: '2025-01-15T06:35:00Z', module: 'Assurance', actor: 'Mapping-Service', hash: 'sha256:map-c7e4f1', status: 'mapped', description: 'Evidence mapped to controls: A.13.1.1, Req 1.1, PR.AC-5' },
    ],
  },
  {
    id: 'EVD-2025-002', asset: 'Active Directory (AD-001)', source: 'Strike Engine', framework: 'ISO 27001',
    control: 'A.9.1.1', controlRef: 'A.9.1.1', evidenceType: 'automated_scan', validationStatus: 'validated',
    timestamp: '2025-01-15T05:15:00Z', confidenceScore: 0.94, owner: 'IAM Team',
    immutableHash: 'sha256:b5d3e9f1a3c5e7f9a1b3d5e7f9a1c3e5d7f9a1b3c5e7d9a1b3c5e7f9a1b3c5',
    description: 'AD access control policy validation confirming proper RBAC implementation.',
    metadata: { scanType: 'Access Control Audit', scanner: 'CyBreach Strike v3.2', duration: '6m 18s' },
    linkedControls: ['A.9.1.1', 'PR.AC-1', 'Req 7.1'], linkedRisks: ['RISK-008', 'RISK-009'], linkedReports: ['RPT-2025-001'],
    auditTrail: [
      { id: 'ae-004', timestamp: '2025-01-15T05:15:00Z', module: 'Strike Engine', actor: 'Strike-Scanner-02', hash: 'sha256:gen-b5d3e9', status: 'generated', description: 'Evidence generated from AD scan' },
      { id: 'ae-005', timestamp: '2025-01-15T05:17:45Z', module: 'Validator', actor: 'Validator-Service', hash: 'sha256:val-c7e4f1', status: 'validated', description: 'Evidence validated - RBAC checks passed' },
      { id: 'ae-006', timestamp: '2025-01-15T05:20:00Z', module: 'Assurance', actor: 'Mapping-Service', hash: 'sha256:map-d8f5a2', status: 'mapped', description: 'Evidence mapped to controls: A.9.1.1, PR.AC-1, Req 7.1' },
    ],
  },
  {
    id: 'EVD-2025-003', asset: 'Payment Gateway (PG-001)', source: 'Strike Engine', framework: 'PCI-DSS',
    control: 'Req 3.5', controlRef: 'Req 3.5', evidenceType: 'automated_scan', validationStatus: 'validated',
    timestamp: '2025-01-14T22:00:00Z', confidenceScore: 0.98, owner: 'Security Engineering',
    immutableHash: 'sha256:c7e4f1a3b5d7e9f1a3c5e7d9a1b3c5e7f9a1d3c5e7f9a1b3d5e7f9a1b3c5d7',
    description: 'Payment card data encryption validation - AES-256 encryption verified in transit and at rest.',
    metadata: { scanType: 'Encryption Audit', scanner: 'CyBreach Strike v3.2', duration: '3m 45s' },
    linkedControls: ['A.10.1.1', 'Req 3.5', 'Art. 32(1)(a)'], linkedRisks: ['RISK-010', 'RISK-015'], linkedReports: ['RPT-2025-002'],
    auditTrail: [
      { id: 'ae-007', timestamp: '2025-01-14T22:00:00Z', module: 'Strike Engine', actor: 'Strike-Scanner-03', hash: 'sha256:gen-c7e4f1', status: 'generated', description: 'Evidence generated from encryption scan' },
      { id: 'ae-008', timestamp: '2025-01-14T22:02:30Z', module: 'Validator', actor: 'Validator-Service', hash: 'sha256:val-d8f5a2', status: 'validated', description: 'Evidence validated - AES-256 encryption confirmed' },
    ],
  },
  {
    id: 'EVD-2025-004', asset: 'Email Server (ES-001)', source: 'Manual Review', framework: 'GDPR',
    control: 'Art. 5', controlRef: 'Art. 5', evidenceType: 'manual_review', validationStatus: 'validated',
    timestamp: '2025-01-14T14:00:00Z', confidenceScore: 0.88, owner: 'DPO Office',
    immutableHash: 'sha256:d8f5a2b4c6e8f0a2b4d6e8f0a2c4d6e8f0a2b4c6d8e0f2a4b6c8d0e2f4a6',
    description: 'Manual review of data processing principles for email communications containing personal data.',
    metadata: { reviewType: 'Privacy Impact Assessment', reviewer: 'Data Protection Officer' },
    linkedControls: ['Art. 5', 'Sec 4'], linkedRisks: ['RISK-012'], linkedReports: ['RPT-2025-003'],
    auditTrail: [
      { id: 'ae-009', timestamp: '2025-01-14T14:00:00Z', module: 'Manual Review', actor: 'DPO-Jane-Smith', hash: 'sha256:gen-d8f5a2', status: 'generated', description: 'Evidence generated from manual review' },
      { id: 'ae-010', timestamp: '2025-01-14T16:30:00Z', module: 'Validator', actor: 'Validator-Service', hash: 'sha256:val-e9f6b3', status: 'validated', description: 'Evidence validated - PIA review complete' },
    ],
  },
  {
    id: 'EVD-2025-005', asset: 'HR Database (HR-DB-001)', source: 'Strike Engine', framework: 'GDPR',
    control: 'Art. 25', controlRef: 'Art. 25', evidenceType: 'configuration', validationStatus: 'expired',
    timestamp: '2024-10-15T09:00:00Z', confidenceScore: 0.55, owner: 'Engineering Security',
    immutableHash: 'sha256:e9f6b3c5d7a1f3c5e7d9a1b3c5e7d9f1a3c5e7d9a1b3c5e7f9a1b3d5e7f9a1',
    description: 'Data protection by design assessment for HR database - evidence has expired.',
    metadata: { scanType: 'DPIA Configuration Check', scanner: 'CyBreach Strike v3.1', duration: '8m 22s' },
    linkedControls: ['Art. 25', 'Sec 7'], linkedRisks: ['RISK-013'], linkedReports: [],
    auditTrail: [
      { id: 'ae-011', timestamp: '2024-10-15T09:00:00Z', module: 'Strike Engine', actor: 'Strike-Scanner-01', hash: 'sha256:gen-e9f6b3', status: 'generated', description: 'Evidence generated from configuration scan' },
      { id: 'ae-012', timestamp: '2024-10-15T09:05:00Z', module: 'Validator', actor: 'Validator-Service', hash: 'sha256:val-f0a7c4', status: 'validated', description: 'Evidence validated - configuration checks passed' },
      { id: 'ae-013', timestamp: '2025-01-10T00:00:00Z', module: 'Assurance', actor: 'Expiry-Service', hash: 'sha256:exp-g1b8d5', status: 'expired', description: 'Evidence expired - 90-day validity period exceeded' },
    ],
  },
  {
    id: 'EVD-2025-006', asset: 'Cloud Infrastructure (AWS)', source: 'Strike Engine', framework: 'NIST CSF',
    control: 'PR.AC-1', controlRef: 'PR.AC-1', evidenceType: 'automated_scan', validationStatus: 'validated',
    timestamp: '2025-01-15T03:45:00Z', confidenceScore: 0.92, owner: 'IAM Team',
    immutableHash: 'sha256:f0a7c4d6e8f0a2c4d6e8f0a2b4d6e8f0a2c4e6d8f0a2b4c6d8e0f2a4b6c8d0',
    description: 'AWS IAM identity and credential management validation - MFA enforced, key rotation verified.',
    metadata: { scanType: 'Cloud IAM Audit', scanner: 'CyBreach Strike v3.2', duration: '5m 10s' },
    linkedControls: ['PR.AC-1', 'A.9.1.1', 'Req 8.1'], linkedRisks: ['RISK-008'], linkedReports: ['RPT-2025-001'],
    auditTrail: [
      { id: 'ae-014', timestamp: '2025-01-15T03:45:00Z', module: 'Strike Engine', actor: 'Strike-Scanner-04', hash: 'sha256:gen-f0a7c4', status: 'generated', description: 'Evidence generated from AWS IAM scan' },
      { id: 'ae-015', timestamp: '2025-01-15T03:48:20Z', module: 'Validator', actor: 'Validator-Service', hash: 'sha256:val-a1b9d6', status: 'validated', description: 'Evidence validated - IAM controls confirmed' },
    ],
  },
  {
    id: 'EVD-2025-007', asset: 'Security Operations Center', source: 'Manual Review', framework: 'ISO 27001',
    control: 'A.12.1.1', controlRef: 'A.12.1.1', evidenceType: 'policy_document', validationStatus: 'validated',
    timestamp: '2025-01-11T13:20:00Z', confidenceScore: 0.90, owner: 'IT Operations',
    immutableHash: 'sha256:a1b9d6c8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0a2',
    description: 'Operational procedures documentation for SOC - incident response and monitoring procedures.',
    metadata: { documentType: 'Standard Operating Procedure', version: '4.2', approver: 'VP Security' },
    linkedControls: ['A.12.1.1', 'PR.IP-1'], linkedRisks: ['RISK-011'], linkedReports: ['RPT-2025-001'],
    auditTrail: [
      { id: 'ae-016', timestamp: '2025-01-11T13:20:00Z', module: 'Manual Review', actor: 'IT-Ops-Mgr', hash: 'sha256:gen-a1b9d6', status: 'generated', description: 'SOP document uploaded' },
      { id: 'ae-017', timestamp: '2025-01-11T15:00:00Z', module: 'Validator', actor: 'Validator-Service', hash: 'sha256:val-b2c0e7', status: 'validated', description: 'Document validated - meets requirements' },
    ],
  },
  {
    id: 'EVD-2025-008', asset: 'Customer Data Platform (CDP-001)', source: 'Strike Engine', framework: 'DPDP',
    control: 'Sec 4', controlRef: 'Sec 4', evidenceType: 'log_evidence', validationStatus: 'pending',
    timestamp: '2025-01-15T07:00:00Z', confidenceScore: 0.0, owner: 'Data Governance',
    immutableHash: 'sha256:b2c0e7d9f1a3c5e7d9f1a3c5e7d9f1a3c5e7d9f1a3b5c7d9e1f3a5b7c9d1e3f5',
    description: 'Consent management log audit - awaiting validation from Module 2.',
    metadata: { scanType: 'Consent Log Audit', scanner: 'CyBreach Strike v3.2', duration: '2m 15s' },
    linkedControls: ['Sec 4', 'Art. 5'], linkedRisks: ['RISK-012'], linkedReports: [],
    auditTrail: [
      { id: 'ae-018', timestamp: '2025-01-15T07:00:00Z', module: 'Strike Engine', actor: 'Strike-Scanner-05', hash: 'sha256:gen-b2c0e7', status: 'generated', description: 'Evidence generated from consent log audit' },
    ],
  },
];

// ==================== RISK DATA ====================
export const risks: Risk[] = [
  { id: 'RISK-001', title: 'Inadequate Security Governance', severity: 'high', likelihood: 3, impact: 4, framework: 'ISO 27001', linkedControls: ['A.5.1.1', 'ID.GV-1'], evidenceCount: 5, assets: ['Enterprise-Wide'], residualRisk: 35, trend: 'decreasing', status: 'mitigated', owner: 'CISO Office', description: 'Risk of insufficient governance structure for information security oversight.' },
  { id: 'RISK-002', title: 'Outdated Security Policies', severity: 'medium', likelihood: 4, impact: 3, framework: 'ISO 27001', linkedControls: ['A.5.1.2'], evidenceCount: 2, assets: ['Enterprise-Wide'], residualRisk: 48, trend: 'stable', status: 'open', owner: 'CISO Office', description: 'Risk of security policies not being reviewed and updated at planned intervals.' },
  { id: 'RISK-003', title: 'Unauthorized Data Access', severity: 'critical', likelihood: 3, impact: 5, framework: 'ISO 27001', linkedControls: ['A.5.1.1', 'A.9.1.1'], evidenceCount: 7, assets: ['AD-001', 'AWS-001'], residualRisk: 22, trend: 'decreasing', status: 'mitigated', owner: 'IAM Team', description: 'Risk of unauthorized access to sensitive data through improper access controls.' },
  { id: 'RISK-004', title: 'Unclear Security Responsibilities', severity: 'medium', likelihood: 3, impact: 3, framework: 'ISO 27001', linkedControls: ['A.6.1.1'], evidenceCount: 4, assets: ['Enterprise-Wide'], residualRisk: 40, trend: 'decreasing', status: 'mitigated', owner: 'HR Security', description: 'Risk of unclear information security roles leading to accountability gaps.' },
  { id: 'RISK-005', title: 'Incomplete Asset Inventory', severity: 'critical', likelihood: 4, impact: 5, framework: 'ISO 27001', linkedControls: ['A.8.1.1', 'ID.AM-1', 'Req 2.4'], evidenceCount: 0, assets: ['All IT Assets'], residualRisk: 85, trend: 'increasing', status: 'open', owner: 'IT Operations', description: 'Risk of unknown or untracked assets leading to security blind spots.' },
  { id: 'RISK-006', title: 'Shadow IT Assets', severity: 'high', likelihood: 5, impact: 4, framework: 'ISO 27001', linkedControls: ['A.8.1.1'], evidenceCount: 0, assets: ['Cloud Services', 'SaaS Applications'], residualRisk: 78, trend: 'increasing', status: 'open', owner: 'IT Operations', description: 'Risk of unapproved IT resources operating outside of security governance.' },
  { id: 'RISK-007', title: 'Data Misclassification', severity: 'high', likelihood: 4, impact: 4, framework: 'ISO 27001', linkedControls: ['A.8.2.1', 'Art. 30'], evidenceCount: 2, assets: ['Data Warehouse', 'CDP-001'], residualRisk: 60, trend: 'stable', status: 'open', owner: 'Data Governance', description: 'Risk of data being classified incorrectly leading to improper security controls.' },
  { id: 'RISK-008', title: 'Privilege Escalation Vulnerability', severity: 'critical', likelihood: 2, impact: 5, framework: 'ISO 27001', linkedControls: ['A.9.1.1', 'PR.AC-1', 'Req 7.1'], evidenceCount: 8, assets: ['AD-001', 'AWS-001', 'Core Firewall'], residualRisk: 18, trend: 'decreasing', status: 'mitigated', owner: 'IAM Team', description: 'Risk of attackers gaining elevated access through privilege escalation.' },
  { id: 'RISK-009', title: 'Orphaned User Accounts', severity: 'medium', likelihood: 3, impact: 3, framework: 'ISO 27001', linkedControls: ['A.9.1.1'], evidenceCount: 3, assets: ['AD-001'], residualRisk: 38, trend: 'decreasing', status: 'open', owner: 'IAM Team', description: 'Risk of dormant user accounts retaining access after employee departure.' },
  { id: 'RISK-010', title: 'Weak Encryption Implementation', severity: 'critical', likelihood: 2, impact: 5, framework: 'PCI-DSS', linkedControls: ['A.10.1.1', 'Req 3.5', 'Art. 32(1)(a)'], evidenceCount: 5, assets: ['PG-001', 'CDP-001'], residualRisk: 25, trend: 'decreasing', status: 'mitigated', owner: 'Security Engineering', description: 'Risk of data exposure due to weak or deprecated encryption algorithms.' },
  { id: 'RISK-011', title: 'Lack of Documented Procedures', severity: 'low', likelihood: 3, impact: 2, framework: 'ISO 27001', linkedControls: ['A.12.1.1'], evidenceCount: 4, assets: ['SOC'], residualRisk: 28, trend: 'stable', status: 'mitigated', owner: 'IT Operations', description: 'Risk of inconsistent operations due to undocumented procedures.' },
  { id: 'RISK-012', title: 'Non-Compliant Data Processing', severity: 'critical', likelihood: 3, impact: 5, framework: 'GDPR', linkedControls: ['Art. 5', 'Sec 4'], evidenceCount: 6, assets: ['HR-DB-001', 'CDP-001'], residualRisk: 30, trend: 'decreasing', status: 'open', owner: 'DPO Office', description: 'Risk of data processing activities not complying with privacy principles.' },
  { id: 'RISK-013', title: 'Privacy by Design Deficiency', severity: 'high', likelihood: 4, impact: 4, framework: 'GDPR', linkedControls: ['Art. 25', 'Sec 7'], evidenceCount: 0, assets: ['Engineering Platform'], residualRisk: 72, trend: 'increasing', status: 'open', owner: 'Engineering Security', description: 'Risk of not embedding privacy measures in system design.' },
  { id: 'RISK-014', title: 'Network Segmentation Gaps', severity: 'critical', likelihood: 3, impact: 5, framework: 'PCI-DSS', linkedControls: ['Req 1.1', 'A.13.1.1', 'PR.AC-5'], evidenceCount: 3, assets: ['Core Firewall', 'DMZ'], residualRisk: 42, trend: 'stable', status: 'open', owner: 'Network Security', description: 'Risk of inadequate network segmentation allowing lateral movement.' },
  { id: 'RISK-015', title: 'Card Data Breach', severity: 'critical', likelihood: 2, impact: 5, framework: 'PCI-DSS', linkedControls: ['Req 3.5', 'A.10.1.1'], evidenceCount: 5, assets: ['PG-001'], residualRisk: 15, trend: 'decreasing', status: 'mitigated', owner: 'Security Engineering', description: 'Risk of payment card data being exposed in a breach.' },
];

// ==================== MISSING EVIDENCE ====================
export const missingEvidenceItems: MissingEvidence[] = [
  { controlId: 'ctrl-004', controlRef: 'A.8.1.1', controlTitle: 'Asset Inventory', framework: 'ISO 27001', issue: 'missing', severity: 'critical', remediation: 'Deploy automated asset discovery tool and conduct physical inventory audit', dueDate: '2025-02-15' },
  { controlId: 'ctrl-010', controlRef: 'Art. 25', controlTitle: 'Data Protection by Design', framework: 'GDPR', issue: 'missing', severity: 'high', remediation: 'Conduct DPIA for all systems processing personal data and document privacy controls', dueDate: '2025-02-28' },
  { controlId: 'ctrl-005', controlRef: 'A.8.2.1', controlTitle: 'Classification of Information', framework: 'ISO 27001', issue: 'weak', severity: 'high', remediation: 'Implement automated data classification tool and classify all data stores', dueDate: '2025-03-01' },
  { controlId: 'ctrl-007', controlRef: 'A.10.1.1', controlTitle: 'Encryption Controls', framework: 'ISO 27001', issue: 'weak', severity: 'medium', remediation: 'Complete encryption audit for all data-at-rest and data-in-transit pathways', dueDate: '2025-02-20' },
  { controlId: 'ctrl-013', controlRef: 'Req 1.1', controlTitle: 'Network Security Controls', framework: 'PCI-DSS', issue: 'weak', severity: 'high', remediation: 'Review and update firewall rules; verify network segmentation controls', dueDate: '2025-02-10' },
  { controlId: 'ctrl-002', controlRef: 'A.5.1.2', controlTitle: 'Review of Information Security Policy', framework: 'ISO 27001', issue: 'expired', severity: 'medium', remediation: 'Schedule policy review meeting and document review outcomes', dueDate: '2025-01-31' },
  { controlId: 'EVD-2025-005', controlRef: 'Art. 25', controlTitle: 'Data Protection by Design', framework: 'GDPR', issue: 'expired', severity: 'high', remediation: 'Re-run DPIA and update evidence with current system configuration', dueDate: '2025-01-25' },
];

// ==================== RESILIENCE SCORE ====================
export const resilienceScore: ResilienceScore = {
  overall: 74,
  compliance: 73,
  risk: 68,
  controlCoverage: 71,
  evidenceCoverage: 78,
  openRisks: 7,
  criticalRisks: 5,
  formula: {
    evidenceConfidence: 0.82,
    controlWeight: 0.30,
    frameworkWeight: 0.25,
    riskWeight: 0.25,
    businessImpact: 0.20,
  },
  history: [
    { date: '2024-07', score: 58 },
    { date: '2024-08', score: 61 },
    { date: '2024-09', score: 63 },
    { date: '2024-10', score: 66 },
    { date: '2024-11', score: 69 },
    { date: '2024-12', score: 71 },
    { date: '2025-01', score: 74 },
  ],
};

// ==================== GAP ANALYSIS ====================
export const gapAnalysis: GapAnalysis = {
  missingControls: [
    { id: 'ctrl-004', title: 'Asset Inventory', framework: 'ISO 27001', priority: 'critical' },
    { id: 'ctrl-010', title: 'Data Protection by Design', framework: 'GDPR', priority: 'high' },
  ],
  weakControls: [
    { id: 'ctrl-005', title: 'Classification of Information', framework: 'ISO 27001', evidence: 2, required: 4 },
    { id: 'ctrl-007', title: 'Encryption Controls', framework: 'ISO 27001', evidence: 3, required: 5 },
    { id: 'ctrl-013', title: 'Network Security Controls', framework: 'PCI-DSS', evidence: 3, required: 5 },
  ],
  highRiskAreas: [
    { name: 'Asset Management', riskCount: 3, framework: 'ISO 27001' },
    { name: 'Data Protection', riskCount: 4, framework: 'GDPR' },
    { name: 'Network Security', riskCount: 2, framework: 'PCI-DSS' },
  ],
  frameworkGaps: [
    { framework: 'DPDP', gap: 37, description: 'Significant gaps in consent management and data principal rights' },
    { framework: 'PCI-DSS', gap: 31, description: 'Network segmentation and vulnerability management gaps' },
    { framework: 'NIST CSF', gap: 29, description: 'Gaps in Identify and Detect functions' },
    { framework: 'ISO 27001', gap: 22, description: 'Asset management and policy review gaps' },
    { framework: 'GDPR', gap: 15, description: 'Privacy by design deficiencies' },
  ],
  evidenceGaps: [
    { framework: 'DPDP', missing: 14, total: 38 },
    { framework: 'PCI-DSS', missing: 20, total: 64 },
    { framework: 'NIST CSF', missing: 31, total: 106 },
    { framework: 'ISO 27001', missing: 20, total: 93 },
    { framework: 'GDPR', missing: 7, total: 46 },
  ],
  recommendations: [
    { title: 'Deploy Automated Asset Discovery', priority: 'critical', impact: 'Reduces RISK-005 and RISK-006 significantly', effort: 'Medium' },
    { title: 'Implement Privacy by Design Framework', priority: 'high', impact: 'Addresses GDPR Art.25 and DPDP Sec.7 gaps', effort: 'High' },
    { title: 'Strengthen Network Segmentation', priority: 'critical', impact: 'Reduces PCI-DSS non-compliance and lateral movement risk', effort: 'Medium' },
    { title: 'Automate Data Classification', priority: 'high', impact: 'Improves ISO 27001 A.8.2.1 compliance', effort: 'Medium' },
    { title: 'Complete Encryption Audit', priority: 'medium', impact: 'Validates encryption controls across frameworks', effort: 'Low' },
    { title: 'Establish Policy Review Cadence', priority: 'medium', impact: 'Ensures timely policy updates', effort: 'Low' },
  ],
};

// ==================== REPORTS ====================
export const reports: Report[] = [
  { id: 'RPT-2025-001', title: 'Q4 2024 ISO 27001 Compliance Report', type: 'ISO Audit', framework: 'ISO 27001', status: 'generated', generatedAt: '2025-01-10T09:00:00Z', businessUnit: 'Enterprise', dateRange: { start: '2024-10-01', end: '2024-12-31' }, complianceScore: 78, resilienceScore: 74, controlsCovered: 73, evidenceLinked: 312, risksIdentified: 5, author: 'Compliance Team', downloaded: true, shared: true },
  { id: 'RPT-2025-002', title: 'PCI-DSS Assessment - Q4 2024', type: 'PCI Audit', framework: 'PCI-DSS', status: 'generated', generatedAt: '2025-01-08T14:00:00Z', businessUnit: 'Payment Services', dateRange: { start: '2024-10-01', end: '2024-12-31' }, complianceScore: 69, resilienceScore: 65, controlsCovered: 44, evidenceLinked: 156, risksIdentified: 3, author: 'Security Engineering', downloaded: false, shared: false },
  { id: 'RPT-2025-003', title: 'GDPR Annual Assessment 2024', type: 'GDPR Assessment', framework: 'GDPR', status: 'generated', generatedAt: '2025-01-05T11:00:00Z', businessUnit: 'Data Privacy', dateRange: { start: '2024-01-01', end: '2024-12-31' }, complianceScore: 85, resilienceScore: 82, controlsCovered: 39, evidenceLinked: 198, risksIdentified: 2, author: 'DPO Office', downloaded: true, shared: true },
  { id: 'RPT-2025-004', title: 'NIST CSF Gap Analysis - January 2025', type: 'NIST Assessment', framework: 'NIST CSF', status: 'pending', generatedAt: '', businessUnit: 'Enterprise', dateRange: { start: '2025-01-01', end: '2025-01-15' }, complianceScore: 71, resilienceScore: 68, controlsCovered: 75, evidenceLinked: 267, risksIdentified: 4, author: 'CISO Office', downloaded: false, shared: false },
  { id: 'RPT-2025-005', title: 'Executive Cybersecurity Summary', type: 'Executive Summary', framework: 'All', status: 'scheduled', scheduledAt: '2025-01-20T08:00:00Z', businessUnit: 'Board', dateRange: { start: '2024-10-01', end: '2024-12-31' }, complianceScore: 73, resilienceScore: 74, controlsCovered: 255, evidenceLinked: 1022, risksIdentified: 15, author: 'CISO', downloaded: false, shared: false },
  { id: 'RPT-2025-006', title: 'DPDP Compliance Readiness Report', type: 'DPDP Report', framework: 'DPDP', status: 'draft', generatedAt: '', businessUnit: 'India Operations', dateRange: { start: '2025-01-01', end: '2025-01-15' }, complianceScore: 62, resilienceScore: 55, controlsCovered: 24, evidenceLinked: 89, risksIdentified: 3, author: 'Data Governance', downloaded: false, shared: false },
];

export const reportTemplates: ReportTemplate[] = [
  { id: 'tpl-001', name: 'Executive Summary', description: 'High-level compliance and risk summary for board and executive stakeholders', category: 'Executive', lastUsed: '2025-01-10', usageCount: 24 },
  { id: 'tpl-002', name: 'ISO 27001 Audit Report', description: 'Comprehensive ISO 27001 audit report with control mapping and evidence references', framework: 'ISO 27001', category: 'Audit', lastUsed: '2025-01-10', usageCount: 18 },
  { id: 'tpl-003', name: 'PCI-DSS Assessment', description: 'PCI-DSS compliance assessment with ROC-style evidence documentation', framework: 'PCI-DSS', category: 'Audit', lastUsed: '2025-01-08', usageCount: 12 },
  { id: 'tpl-004', name: 'GDPR Assessment', description: 'GDPR compliance assessment with data processing records and privacy controls', framework: 'GDPR', category: 'Assessment', lastUsed: '2025-01-05', usageCount: 15 },
  { id: 'tpl-005', name: 'NIST Assessment', description: 'NIST CSF maturity assessment with function-level analysis', framework: 'NIST CSF', category: 'Assessment', lastUsed: '2024-12-20', usageCount: 8 },
  { id: 'tpl-006', name: 'DPDP Compliance Report', description: 'Digital Personal Data Protection Act compliance assessment', framework: 'DPDP', category: 'Compliance', lastUsed: '2024-12-15', usageCount: 5 },
  { id: 'tpl-007', name: 'Risk Assessment Report', description: 'Comprehensive risk assessment with severity analysis and mitigation plans', category: 'Risk', lastUsed: '2025-01-12', usageCount: 20 },
  { id: 'tpl-008', name: 'Board-Level Report', description: 'Strategic cybersecurity posture report for board presentation', category: 'Executive', lastUsed: '2024-12-31', usageCount: 10 },
  { id: 'tpl-009', name: 'Evidence Report', description: 'Detailed evidence inventory with validation status and audit trail', category: 'Evidence', lastUsed: '2025-01-14', usageCount: 14 },
  { id: 'tpl-010', name: 'Gap Analysis Report', description: 'Compliance gap analysis with prioritized remediation recommendations', category: 'Analysis', lastUsed: '2025-01-13', usageCount: 16 },
];

// ==================== NOTIFICATIONS ====================
export const notifications: Notification[] = [
  { id: 'notif-001', type: 'evidence_missing', title: 'Missing Evidence: Asset Inventory', message: 'Control A.8.1.1 (Asset Inventory) has no linked validated evidence. Compliance status: Non-Compliant.', timestamp: '2025-01-15T08:00:00Z', read: false, severity: 'error', source: 'Evidence Monitor' },
  { id: 'notif-002', type: 'evidence_missing', title: 'Missing Evidence: Privacy by Design', message: 'Control Art. 25 (Data Protection by Design) lacks validated evidence. Immediate action required.', timestamp: '2025-01-15T07:30:00Z', read: false, severity: 'error', source: 'Evidence Monitor' },
  { id: 'notif-003', type: 'validation_failed', title: 'Evidence Expired', message: 'EVD-2025-005 for Art. 25 has expired. Re-validation required before compliance assessment.', timestamp: '2025-01-15T06:00:00Z', read: false, severity: 'warning', source: 'Validator Service' },
  { id: 'notif-004', type: 'risk_increased', title: 'Risk Escalation: Shadow IT', message: 'RISK-006 (Shadow IT Assets) severity has increased. 5 new unapproved SaaS applications detected.', timestamp: '2025-01-14T16:00:00Z', read: true, severity: 'warning', source: 'Risk Engine' },
  { id: 'notif-005', type: 'framework_updated', title: 'NIST CSF 2.0 Update', message: 'NIST CSF framework definition has been updated to version 2.0.3 with minor control changes.', timestamp: '2025-01-14T12:00:00Z', read: true, severity: 'info', source: 'Framework Service' },
  { id: 'notif-006', type: 'report_generated', title: 'Q4 ISO Audit Report Ready', message: 'RPT-2025-001 has been generated successfully and is ready for download.', timestamp: '2025-01-10T09:00:00Z', read: true, severity: 'success', source: 'Report Engine' },
  { id: 'notif-007', type: 'approval_required', title: 'Report Approval Required', message: 'Executive Cybersecurity Summary (RPT-2025-005) requires CISO approval before generation.', timestamp: '2025-01-13T10:00:00Z', read: false, severity: 'info', source: 'Approval Workflow' },
  { id: 'notif-008', type: 'risk_increased', title: 'Critical Risk: Incomplete Asset Inventory', message: 'RISK-005 remains open with no evidence linked. Residual risk at 85%.', timestamp: '2025-01-15T04:00:00Z', read: false, severity: 'error', source: 'Risk Engine' },
];

// ==================== CHART DATA ====================
export const complianceTrendData = [
  { month: 'Jul', iso: 65, gdpr: 72, nist: 58, dpdp: 45, pci: 60 },
  { month: 'Aug', iso: 68, gdpr: 75, nist: 61, dpdp: 48, pci: 62 },
  { month: 'Sep', iso: 70, gdpr: 78, nist: 63, dpdp: 50, pci: 64 },
  { month: 'Oct', iso: 73, gdpr: 80, nist: 65, dpdp: 53, pci: 66 },
  { month: 'Nov', iso: 75, gdpr: 83, nist: 68, dpdp: 57, pci: 67 },
  { month: 'Dec', iso: 77, gdpr: 84, nist: 70, dpdp: 60, pci: 68 },
  { month: 'Jan', iso: 78, gdpr: 85, nist: 71, dpdp: 62, pci: 69 },
];

export const evidenceTrendData = [
  { week: 'W1', validated: 45, pending: 8, expired: 3, rejected: 1 },
  { week: 'W2', validated: 52, pending: 6, expired: 2, rejected: 0 },
  { week: 'W3', validated: 58, pending: 10, expired: 4, rejected: 2 },
  { week: 'W4', validated: 65, pending: 7, expired: 3, rejected: 1 },
  { week: 'W5', validated: 70, pending: 5, expired: 2, rejected: 0 },
  { week: 'W6', validated: 78, pending: 9, expired: 3, rejected: 1 },
];

export const riskDistributionData = [
  { name: 'Critical', value: 5, color: '#EF4444' },
  { name: 'High', value: 4, color: '#F59E0B' },
  { name: 'Medium', value: 3, color: '#3B82F6' },
  { name: 'Low', value: 2, color: '#22C55E' },
  { name: 'Negligible', value: 1, color: '#94A3B8' },
];

export const frameworkCoverageData = [
  { framework: 'ISO 27001', coverage: 78, target: 85 },
  { framework: 'GDPR', coverage: 85, target: 90 },
  { framework: 'NIST CSF', coverage: 71, target: 80 },
  { framework: 'DPDP', coverage: 62, target: 75 },
  { framework: 'PCI-DSS', coverage: 69, target: 85 },
];

export const departmentResilienceData = [
  { department: 'Engineering', score: 82 },
  { department: 'Finance', score: 75 },
  { department: 'Operations', score: 68 },
  { department: 'Legal', score: 85 },
  { department: 'HR', score: 72 },
  { department: 'Marketing', score: 65 },
];

export const riskMatrixData = [
  { impact: 5, likelihood: 1, count: 2, label: 'Critical' },
  { impact: 5, likelihood: 2, count: 1, label: 'Critical' },
  { impact: 4, likelihood: 2, count: 1, label: 'High' },
  { impact: 4, likelihood: 3, count: 2, label: 'High' },
  { impact: 4, likelihood: 4, count: 1, label: 'High' },
  { impact: 3, likelihood: 3, count: 2, label: 'Medium' },
  { impact: 3, likelihood: 4, count: 1, label: 'Medium' },
  { impact: 2, likelihood: 3, count: 1, label: 'Low' },
];

export const controlStatusData = [
  { name: 'Compliant', value: 8, color: '#22C55E' },
  { name: 'Partially Compliant', value: 4, color: '#F59E0B' },
  { name: 'Non-Compliant', value: 2, color: '#EF4444' },
  { name: 'Not Assessed', value: 0, color: '#94A3B8' },
];

// ==================== TASK DATA ====================
import type { GrcTask } from './types';

export const tasks: GrcTask[] = [
  {
    id: 'TASK-001',
    title: 'Collect evidence for A.8.1.1 Asset Inventory',
    description: 'Deploy automated asset discovery tool and document all IT assets across the organization. This control currently has zero evidence and is marked non-compliant.',
    type: 'evidence_collection',
    status: 'todo',
    priority: 'critical',
    assignee: 'IT Operations',
    assigneeInitials: 'IO',
    framework: 'ISO 27001',
    controlRef: 'A.8.1.1',
    dueDate: '2025-02-15',
    createdAt: '2025-01-10T09:00:00Z',
    progress: 0,
    tags: ['asset-management', 'critical-gap'],
  },
  {
    id: 'TASK-002',
    title: 'Conduct DPIA for HR Database System',
    description: 'Perform Data Protection Impact Assessment for HR-DB-001 as required by GDPR Art. 25. Evidence has expired and needs revalidation.',
    type: 'evidence_collection',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Engineering Security',
    assigneeInitials: 'ES',
    framework: 'GDPR',
    controlRef: 'Art. 25',
    dueDate: '2025-01-25',
    createdAt: '2025-01-08T14:00:00Z',
    progress: 45,
    tags: ['privacy', 'expired-evidence'],
  },
  {
    id: 'TASK-003',
    title: 'Review and update Information Security Policy',
    description: 'Schedule policy review meeting with CISO and document outcomes. Policy is overdue for scheduled review per A.5.1.2.',
    type: 'review',
    status: 'review',
    priority: 'medium',
    assignee: 'CISO Office',
    assigneeInitials: 'CO',
    framework: 'ISO 27001',
    controlRef: 'A.5.1.2',
    dueDate: '2025-01-31',
    createdAt: '2025-01-05T10:00:00Z',
    progress: 80,
    tags: ['policy', 'overdue-review'],
  },
  {
    id: 'TASK-004',
    title: 'Complete encryption audit for data-at-rest',
    description: 'Verify AES-256 encryption across all data stores. Control A.10.1.1 has insufficient evidence (3 of 5 required).',
    type: 'control_testing',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Security Engineering',
    assigneeInitials: 'SE',
    framework: 'ISO 27001',
    controlRef: 'A.10.1.1',
    dueDate: '2025-02-20',
    createdAt: '2025-01-12T11:00:00Z',
    progress: 60,
    tags: ['encryption', 'partial-evidence'],
  },
  {
    id: 'TASK-005',
    title: 'Strengthen network segmentation controls',
    description: 'Review and update firewall rules for PCI-DSS Req 1.1 compliance. Verify DMZ isolation and cardholder network segmentation.',
    type: 'remediation',
    status: 'todo',
    priority: 'critical',
    assignee: 'Network Security',
    assigneeInitials: 'NS',
    framework: 'PCI-DSS',
    controlRef: 'Req 1.1',
    dueDate: '2025-02-10',
    createdAt: '2025-01-11T08:00:00Z',
    progress: 0,
    tags: ['network', 'segmentation', 'critical'],
  },
  {
    id: 'TASK-006',
    title: 'Implement automated data classification',
    description: 'Deploy data classification tool and classify all data stores per A.8.2.1. Currently only 2 of 4 required evidence items available.',
    type: 'remediation',
    status: 'todo',
    priority: 'high',
    assignee: 'Data Governance',
    assigneeInitials: 'DG',
    framework: 'ISO 27001',
    controlRef: 'A.8.2.1',
    dueDate: '2025-03-01',
    createdAt: '2025-01-09T13:00:00Z',
    progress: 15,
    tags: ['data-classification', 'automation'],
  },
  {
    id: 'TASK-007',
    title: 'Q1 2025 ISO 27001 Internal Audit',
    description: 'Prepare for and conduct internal audit of ISO 27001 controls. Review all evidence and compliance documentation.',
    type: 'audit_prep',
    status: 'todo',
    priority: 'high',
    assignee: 'Compliance Team',
    assigneeInitials: 'CT',
    framework: 'ISO 27001',
    dueDate: '2025-03-15',
    createdAt: '2025-01-13T09:00:00Z',
    progress: 0,
    tags: ['audit', 'q1-2025'],
  },
  {
    id: 'TASK-008',
    title: 'Approve Executive Cybersecurity Summary',
    description: 'Report RPT-2025-005 requires CISO approval before scheduled generation on Jan 20.',
    type: 'approval',
    status: 'review',
    priority: 'high',
    assignee: 'CISO',
    assigneeInitials: 'CI',
    framework: 'All',
    dueDate: '2025-01-19',
    createdAt: '2025-01-13T10:00:00Z',
    progress: 90,
    tags: ['report', 'approval', 'executive'],
  },
  {
    id: 'TASK-009',
    title: 'Remediate Shadow IT findings',
    description: '5 new unapproved SaaS applications detected. Inventory and assess risk of all shadow IT assets.',
    type: 'remediation',
    status: 'blocked',
    priority: 'critical',
    assignee: 'IT Operations',
    assigneeInitials: 'IO',
    framework: 'ISO 27001',
    controlRef: 'A.8.1.1',
    dueDate: '2025-02-28',
    createdAt: '2025-01-14T16:00:00Z',
    progress: 25,
    tags: ['shadow-it', 'blocked', 'critical'],
  },
  {
    id: 'TASK-010',
    title: 'Revalidate consent management logs',
    description: 'Evidence EVD-2025-008 for DPDP Sec 4 is pending validation. Follow up with Validator module.',
    type: 'evidence_collection',
    status: 'in_progress',
    priority: 'medium',
    assignee: 'Data Governance',
    assigneeInitials: 'DG',
    framework: 'DPDP',
    controlRef: 'Sec 4',
    dueDate: '2025-01-22',
    createdAt: '2025-01-15T07:00:00Z',
    progress: 50,
    tags: ['consent', 'pending-validation'],
  },
  {
    id: 'TASK-011',
    title: 'Complete NIST CSF gap assessment',
    description: 'Finalize gap analysis for NIST CSF 2.0 controls. 31 controls still need evidence mapping.',
    type: 'control_testing',
    status: 'done',
    priority: 'medium',
    assignee: 'Compliance Team',
    assigneeInitials: 'CT',
    framework: 'NIST CSF',
    dueDate: '2025-01-10',
    createdAt: '2024-12-20T09:00:00Z',
    progress: 100,
    tags: ['nist', 'gap-analysis', 'completed'],
  },
  {
    id: 'TASK-012',
    title: 'Update access control policy documentation',
    description: 'Document updated RBAC implementation per A.9.1.1. Include MFA enforcement details.',
    type: 'review',
    status: 'done',
    priority: 'low',
    assignee: 'IAM Team',
    assigneeInitials: 'IA',
    framework: 'ISO 27001',
    controlRef: 'A.9.1.1',
    dueDate: '2025-01-12',
    createdAt: '2024-12-28T10:00:00Z',
    progress: 100,
    tags: ['access-control', 'documentation'],
  },
];
